### ISSUE TITLE
std::bad_alloc on parsing planet pbf

### ISSUE THREAD

**Issue by geohacker** [geohacker/osmlazer#1]
Ran into this while running this code https://github.com/geohacker/osmlazer/blob/8becbcf608e5db99d6bb2c586bf9c049d8561957/index.js against planet pbf:

```
penny@ip-172-31-14-40:/mnt/data/osmlazer$ node index.js --file 11102016174530.osm.pbf



/mnt/data/osmlazer/node_modules/osmium/lib/osmium.js:100
    return this._reader.read();
                        ^

Error: osmium error: std::bad_alloc
    at Error (native)
    at exports.Reader.read (/mnt/data/osmlazer/node_modules/osmium/lib/osmium.js:100:25)
    at exports.Stream._read_object (/mnt/data/osmlazer/node_modules/osmium/lib/osmium.js:194:37)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

@springmeyer  @joto - do you have thoughts on what could be wrong and tips on what we can try? I was running this on a c3.8x large instance with 60G of memory and 640G of SSD.

**Comment by joto** [comment]
`new osmium.LocationHandler()` will give you a default location handler which is a "sparse_mem_array". That is only suitable for small and medium sized extracts. For planets use `new osmium.LocationHandler("dense_mmap_array")`.

But you are not using the location at all. So it would be even simpler to just get rid of it. :-)

**Comment by geohacker** [comment]
@joto ah right, yes in this case I got rid of the location handler to solve the problem, but good to note about the cache strategy. Thank you!
