### ISSUE TITLE
Experience / questions using osmlazer

### ISSUE THREAD

**Issue by bkowshik** [geohacker/osmlazer#4]
Thank you @geohacker for the package, super useful! 👍 

---

## Single threaded
From what I understand, the package is single threaded. This makes processing large `pbf` files like the entire osm planet, etc take too long. Is my understanding correct about the single threaded nature of `osmlazer`? What are the alternatives to process features in parallel to scale to large `pbf` files?

## visible: true
The features have an interesting property in `visible`. But, when I checked the value for visible is `true` for all the features in Bengaluru. Not sure what this field is or how to use it.

## orig_id and from_way tags
Looks like the features through the stream come twice with slightly different properties. I don't understand why the features come up twice in the stream with slightly different properties. Ex:

First occurrence of the feature with the following properties is something I expected.
```
{
    ...
    "name": "Chunchagatta Lake",
    "nodes_count": 26,
    "type": "way",
    "visible": true,
    "id": 33541358
    ...
}
```

Second occurrence of the feature which was interesting had a few different properties.
```
{
    ...
    "name": "Chunchagatta Lake",
    "from_way": true,
    "orig_id": 33541358,
    "type": "area",
    "visible": true,
    "id": 67082716
    ...
}
```

---

Sorry for the long post, would be super helpful to understand more about ^

**Comment by geohacker** [comment]
> Single threaded

We use osmium's streams and I'm not sure how multiple threads would work in this case. File isn't parsed sequentially if that's what you mean. 

> visible: true

This is to indicate whether a feature is visible on the map or deleted. Deleted features don't have geometries but `visible: false`

> orig_id and from_way tags

I don't 100% understand this, but my hunch is because they are members of another feature. To get the geometry reliable we use the node cache.

**Comment by geohacker** [comment]
Thank you for using osmlazer - it's nowhere close to done and tested so any questions/tickets will help! 🙇

**Comment by bkowshik** [comment]
I looked into features that came in twice from the stream from the version `1` lakes in Bengaluru. I got back `15` features from the script.

- Gist with data: https://gist.github.com/bkowshik/7033981c4aed889b185026899bf50bdc

Looks like, if the feature's type is `way`, it comes up twice in the stream. Ex: [way/477222112](http://www.openstreetmap.org/way/477222112)
- First as a [`LineString` with all the feature properties](https://gist.github.com/bkowshik/7033981c4aed889b185026899bf50bdc#file-part-1-of-duplicate-feature-txt) and
- Second as a [`MultiPolygon` with `from_way` and `orig_id` properties](https://gist.github.com/bkowshik/7033981c4aed889b185026899bf50bdc#file-part-2-of-duplicate-feature-txt).

*NOTE: The links ^ point to a gist with raw data.*

<img width="1227" alt="screen shot 2017-03-24 at 12 09 47 pm" src="https://cloud.githubusercontent.com/assets/2899501/24283283/d3344bd8-108a-11e7-87cb-11fdbbab7588.png">

But, this is not the case when the feature is a `relation`. Ex: [relation/6820030](http://www.openstreetmap.org/relation/6820030) where there is no feature of type `LineString`, there is just **one feature** of type MultiPolygon.

<img width="1226" alt="screen shot 2017-03-24 at 12 13 55 pm" src="https://cloud.githubusercontent.com/assets/2899501/24283410/9427b730-108b-11e7-82eb-544d20345af9.png">

---

cc: @planemad

**Comment by geohacker** [comment]
cc @joto for help!

**Comment by joto** [comment]
Osmium doesn't know whether a closed way is to be handled as a LineString (that just happens to be closed) or a Polygon, so it gives you both. It is the job of the application to look at the tags and decide which tags it want's to handle in this or that way. This is just Osmium being super-generic and not trying to interpret tags for you that you might want to interpret differently.

**Comment by planemad** [comment]
@joto is [osmpgsql dafault.style](https://github.com/openstreetmap/osm2pgsql) the best reference to use to interpret geometry of OSM tags?

**Comment by joto** [comment]
@planemad Probably. There is also a list in [minjur](https://github.com/mapbox/minjur/blob/master/minjur.cpp#L65-L160). I keep wanting to create a more comprehensive list (semi-)automatically, but never got around to it.

**Comment by bkowshik** [comment]
Thank you everybody, no next actions here. Closing.
